- name: ec2instance-playbook
  hosts: host
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name:
          - docker.io
          - python3-pip
        state: present

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present
        executable: pip3

    - name: Create a docker network
      docker_network:
        name: test

    - name: Re-create a Spring container
      docker_container:
        name: bin9638-springboot
        image: bin9638/springboot
        networks:
          - name: test
            aliases:
              - test
        state: started
        recreate: yes
        exposed_ports:
          - 8080
        detach: true
        published_ports:
          - 8081:8080
        pull: true
        comparisons:
          image: strict

    - name: Prune everything
      community.docker.docker_prune:
        containers: true
        images: true