- name: Install Jenkins
  hosts: host
  become: yes
  become_user: root
  become_method: sudo
  vars:
    java_package: "openjdk-11-jdk"
    jenkins_apt_key: "https://pkg.jenkins.io/debian/jenkins.io.key"
    jenkins_deb_repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    jenkins_packages:
      - jenkins
  tasks:
    - name: Install OpenJDK 11
      apt:
        name: "{{ java_package }}"
        state: present
        update_cache: yes

    - name: Add Jenkins APT key
      apt_key:
        url: "{{ jenkins_apt_key }}"
        state: present

    - name: Add Jenkins Debian repository
      apt_repository:
        repo: "{{ jenkins_deb_repo }}"
        state: present

    - name: Update apt and install Jenkins
      apt:
        name: "{{ jenkins_packages }}"
        state: present
        update_cache: yes